-- =============================================================================
-- Demo catalogue (docs/11 §6–§7) — LOCAL AND STAGING ONLY.
--
-- Production gets the real catalogue (docs/11 preamble). Brand names are used as
-- realistic fixtures; logos and photography are placeholders and MUST be replaced with
-- authorised assets before launch (docs/11 §5).
--
-- Idempotent: fixed UUIDs plus `on conflict do update`, so `db reset` and repeated
-- `db push --include-seed` produce identical state.
--
-- Content note: descriptions here are 2–3 sentences. docs/11 §7 asks for ~120 words per
-- product; expanding them is content work, not schema work, and is tracked in
-- docs/14 §3. Every claim below stays inside the permissible-function wording of
-- docs/08 §7.2 — no treats/cures/prevents anywhere.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Ingredients (docs/11 §6)
-- -----------------------------------------------------------------------------
insert into ingredients (id, slug, name, other_names, summary, benefits, dosage_notes, safety_notes, evidence, category) values
 ('a0000000-0000-4000-8000-000000000001','vitamin-c','{"sq":"Vitamina C","en":"Vitamin C"}','{"Ascorbic acid","Acid askorbik"}','{"sq":"Vitaminë e tretshme në ujë që trupi nuk e ruan, ndaj duhet marrë çdo ditë.","en":"A water-soluble vitamin the body does not store, so it is needed daily."}','{"sq":"Kontribuon në funksionimin normal të sistemit imunitar dhe në formimin normal të kolagjenit.","en":"Contributes to the normal function of the immune system and to normal collagen formation."}','{"sq":"80–1000 mg në ditë, me ushqim.","en":"80–1000 mg daily, with food."}','{"sq":"Doza të larta mund të shkaktojnë çrregullime të lehta të tretjes.","en":"High doses may cause mild digestive upset."}','strong','vitamin'),
 ('a0000000-0000-4000-8000-000000000002','vitamin-d3','{"sq":"Vitamina D3","en":"Vitamin D3"}','{"Cholecalciferol","Kolekalciferol"}','{"sq":"Prodhohet në lëkurë nga dielli; nivelet bien në dimër në gjerësitë tona.","en":"Made in the skin from sunlight; levels fall in winter at our latitudes."}','{"sq":"Kontribuon në përthithjen normale të kalciumit dhe në ruajtjen e kockave normale.","en":"Contributes to normal calcium absorption and to the maintenance of normal bones."}','{"sq":"1000–4000 IU në ditë, me një vakt që përmban yndyrë.","en":"1000–4000 IU daily, with a meal containing fat."}','{"sq":"Mos kalo 4000 IU në ditë pa këshillë profesionale.","en":"Do not exceed 4000 IU daily without professional advice."}','strong','vitamin'),
 ('a0000000-0000-4000-8000-000000000003','vitamin-b12','{"sq":"Vitamina B12","en":"Vitamin B12"}','{"Cobalamin","Metilkobalamin"}','{"sq":"Gjendet natyrshëm vetëm në ushqime shtazore, ndaj ka rëndësi për dietat vegane.","en":"Found naturally only in animal foods, so it matters on vegan diets."}','{"sq":"Kontribuon në metabolizmin normal të energjisë dhe në reduktimin e lodhjes.","en":"Contributes to normal energy metabolism and to the reduction of tiredness."}','{"sq":"250–1000 µg në ditë.","en":"250–1000 µg daily."}','{"sq":"E sigurt në doza të larta; nuk grumbullohet.","en":"Safe at high intakes; it does not accumulate."}','strong','vitamin'),
 ('a0000000-0000-4000-8000-000000000004','b-complex','{"sq":"Kompleksi B","en":"B-Complex"}','{"Vitamin B complex"}','{"sq":"Të tetë vitaminat B së bashku, që punojnë në rrugët e energjisë.","en":"All eight B vitamins together, working across the energy pathways."}','{"sq":"Kontribuojnë në metabolizmin normal të energjisë dhe në funksionimin normal të sistemit nervor.","en":"Contribute to normal energy metabolism and to normal nervous system function."}','{"sq":"Një dozë në mëngjes, me ushqim.","en":"One dose in the morning, with food."}','{"sq":"Mund të ngjyrosë urinën të verdhë — e padëmshme.","en":"May turn urine bright yellow — harmless."}','moderate','vitamin'),
 ('a0000000-0000-4000-8000-000000000005','magnesium','{"sq":"Magnezi bisglicinat","en":"Magnesium bisglycinate"}','{"Magnesium glycinate"}','{"sq":"Formë e lidhur me glicinë, e tolerueshme mirë nga stomaku.","en":"A glycine-bound form that is gentle on the stomach."}','{"sq":"Kontribuon në funksionimin normal të muskujve dhe në reduktimin e lodhjes.","en":"Contributes to normal muscle function and to the reduction of tiredness."}','{"sq":"200–400 mg në mbrëmje.","en":"200–400 mg in the evening."}','{"sq":"Doza të larta mund të kenë efekt laksativ.","en":"High doses may have a laxative effect."}','moderate','mineral'),
 ('a0000000-0000-4000-8000-000000000006','zinc','{"sq":"Zinku","en":"Zinc"}','{"Zinc picolinate"}','{"sq":"Mineral gjurmë i nevojshëm për shumë enzima.","en":"A trace mineral required by many enzymes."}','{"sq":"Kontribuon në funksionimin normal të sistemit imunitar dhe në ruajtjen e lëkurës normale.","en":"Contributes to normal immune function and to the maintenance of normal skin."}','{"sq":"10–25 mg në ditë, me ushqim.","en":"10–25 mg daily, with food."}','{"sq":"Me stomak bosh mund të shkaktojë nauze.","en":"May cause nausea on an empty stomach."}','strong','mineral'),
 ('a0000000-0000-4000-8000-000000000007','omega-3','{"sq":"Omega-3 EPA/DHA","en":"Omega-3 EPA/DHA"}','{"Fish oil","Vaj peshku"}','{"sq":"Acide yndyrore të gjata nga peshku i ujërave të ftohta.","en":"Long-chain fatty acids from cold-water fish."}','{"sq":"DHA dhe EPA kontribuojnë në funksionimin normal të zemrës.","en":"DHA and EPA contribute to normal heart function."}','{"sq":"250–1000 mg EPA+DHA në ditë, me vakt.","en":"250–1000 mg EPA+DHA daily, with a meal."}','{"sq":"Bisedo me mjekun nëse merr antikoagulantë.","en":"Speak to your doctor if you take anticoagulants."}','strong','fatty_acid'),
 ('a0000000-0000-4000-8000-000000000008','collagen','{"sq":"Peptidet e kolagjenit","en":"Collagen peptides"}','{"Hydrolysed collagen"}','{"sq":"Kolagjen i hidrolizuar në fragmente të vogla, që tretet lehtë në lëngje.","en":"Collagen hydrolysed into small fragments that dissolve easily in liquid."}','{"sq":"Shpesh kombinohet me vitaminë C, që kontribuon në formimin normal të kolagjenit.","en":"Often combined with vitamin C, which contributes to normal collagen formation."}','{"sq":"5–10 g në ditë, në ujë ose kafe.","en":"5–10 g daily, in water or coffee."}','{"sq":"Nuk është i përshtatshëm për dietat vegane.","en":"Not suitable for vegan diets."}','moderate','protein'),
 ('a0000000-0000-4000-8000-000000000009','creatine','{"sq":"Kreatina monohidrat","en":"Creatine monohydrate"}','{"Creapure"}','{"sq":"Suplementi sportiv më i studiuar; ndihmon rezervat e energjisë në muskul.","en":"The most studied sports supplement; supports energy stores in muscle."}','{"sq":"Rrit performancën fizike në seri të njëpasnjëshme me intensitet të lartë.","en":"Increases physical performance in successive bursts of high-intensity exercise."}','{"sq":"3–5 g në ditë, kurdo.","en":"3–5 g daily, at any time."}','{"sq":"Pi ujë të bollshëm gjatë ditës.","en":"Drink plenty of water through the day."}','strong','amino_acid'),
 ('a0000000-0000-4000-8000-00000000000a','whey-protein','{"sq":"Proteina whey","en":"Whey protein"}','{"Whey isolate","Whey concentrate"}','{"sq":"Proteinë e qumështit me profil të plotë aminoacidesh, që përthithet shpejt.","en":"A complete-amino-acid milk protein that absorbs quickly."}','{"sq":"Proteina kontribuon në rritjen dhe ruajtjen e masës muskulore.","en":"Protein contributes to the growth and maintenance of muscle mass."}','{"sq":"20–30 g pas stërvitjes ose gjatë ditës.","en":"20–30 g after training or through the day."}','{"sq":"Përmban laktozë; jo për alergji ndaj qumështit.","en":"Contains lactose; not for milk allergy."}','strong','protein'),
 ('a0000000-0000-4000-8000-00000000000b','plant-protein','{"sq":"Proteina bimore","en":"Plant protein blend"}','{"Pea and rice protein"}','{"sq":"Përzierje bizele dhe orizi, që së bashku dhurojnë profil të plotë.","en":"A pea and rice blend that together gives a complete profile."}','{"sq":"Proteina kontribuon në ruajtjen e masës muskulore.","en":"Protein contributes to the maintenance of muscle mass."}','{"sq":"25–30 g pas stërvitjes.","en":"25–30 g after training."}','{"sq":"Pa qumësht dhe pa soje.","en":"Free from dairy and soy."}','moderate','protein'),
 ('a0000000-0000-4000-8000-00000000000c','ashwagandha','{"sq":"Ashwagandha KSM-66","en":"Ashwagandha KSM-66"}','{"Withania somnifera"}','{"sq":"Bimë adaptogjene e përdorur në ajurvedë, e standardizuar në withanolide.","en":"An adaptogenic herb used in Ayurveda, standardised for withanolides."}','{"sq":"Përdoret tradicionalisht për ndjesinë e qetësisë në ditët e ngarkuara.","en":"Traditionally used for a sense of calm on demanding days."}','{"sq":"300–600 mg në ditë.","en":"300–600 mg daily."}','{"sq":"Nuk rekomandohet në shtatzëni ose gjidhënie.","en":"Not recommended in pregnancy or while breastfeeding."}','moderate','herb'),
 ('a0000000-0000-4000-8000-00000000000d','rhodiola','{"sq":"Rhodiola rosea","en":"Rhodiola rosea"}','{"Golden root"}','{"sq":"Bimë alpine e përdorur tradicionalisht në ditët e gjata.","en":"An alpine herb traditionally used through long days."}','{"sq":"Përdorim tradicional për ndjesinë e vitalitetit.","en":"Traditional use for a sense of vitality."}','{"sq":"200–400 mg në mëngjes.","en":"200–400 mg in the morning."}','{"sq":"Mund të ndikojë gjumin nëse merret në mbrëmje.","en":"May affect sleep if taken late in the day."}','emerging','herb'),
 ('a0000000-0000-4000-8000-00000000000e','melatonin','{"sq":"Melatonina","en":"Melatonin"}','{"N-acetyl-5-methoxytryptamine"}','{"sq":"Hormon që trupi prodhon në mbrëmje si sinjal i gjumit.","en":"A hormone the body makes in the evening as a sleep signal."}','{"sq":"Kontribuon në reduktimin e kohës së nevojshme për të zënë gjumin.","en":"Contributes to the reduction of time taken to fall asleep."}','{"sq":"1 mg 30 minuta para gjumit.","en":"1 mg thirty minutes before bed."}','{"sq":"Mund të shkaktojë përgjumje. Jo në shtatzëni, gjidhënie, nën 18 vjeç, ose para vozitjes.","en":"May cause drowsiness. Not for pregnancy, breastfeeding, under 18s, or before driving."}','strong','other'),
 ('a0000000-0000-4000-8000-00000000000f','curcumin','{"sq":"Kurkumina","en":"Curcumin"}','{"Turmeric extract","Ekstrakt shafrani i Indisë"}','{"sq":"Përbërësi i verdhë i shafranit të Indisë, i marrë më mirë me piperinë.","en":"The yellow compound in turmeric, better absorbed with piperine."}','{"sq":"Përdorim tradicional për rehatinë e nyjeve.","en":"Traditional use for joint comfort."}','{"sq":"500 mg në ditë me ushqim.","en":"500 mg daily with food."}','{"sq":"Bisedo me mjekun nëse merr antikoagulantë.","en":"Speak to your doctor if you take anticoagulants."}','moderate','herb'),
 ('a0000000-0000-4000-8000-000000000010','probiotic','{"sq":"Përzierje probiotike","en":"Probiotic blend"}','{"Lactobacillus","Bifidobacterium"}','{"sq":"Kultura të gjalla bakteriale, të matura në CFU.","en":"Live bacterial cultures, measured in CFU."}','{"sq":"Përdoren gjerësisht si pjesë e një rutine të ekuilibrit të tretjes.","en":"Widely used as part of a digestive balance routine."}','{"sq":"10 miliardë CFU në ditë, me stomak bosh.","en":"10 billion CFU daily, on an empty stomach."}','{"sq":"Ruaj në frigorifer pas hapjes.","en":"Refrigerate after opening."}','moderate','other'),
 ('a0000000-0000-4000-8000-000000000011','psyllium','{"sq":"Fibra e psyllium","en":"Psyllium fibre"}','{"Plantago ovata"}','{"sq":"Fibër e tretshme që formon gel me ujë.","en":"A soluble fibre that forms a gel with water."}','{"sq":"Kontribuon në funksionimin normal të zorrëve.","en":"Contributes to normal bowel function."}','{"sq":"5 g me një gotë të plotë uji.","en":"5 g with a full glass of water."}','{"sq":"Merr gjithmonë me shumë lëng.","en":"Always take with plenty of liquid."}','strong','fibre'),
 ('a0000000-0000-4000-8000-000000000012','electrolytes','{"sq":"Kompleks elektrolitesh","en":"Electrolyte complex"}','{"Sodium, potassium, magnesium"}','{"sq":"Kripa që humbasin me djersën gjatë stërvitjes ose vapës.","en":"The salts lost in sweat during training or hot weather."}','{"sq":"Ndihmojnë ruajtjen e hidratimit normal gjatë aktivitetit.","en":"Support normal hydration during activity."}','{"sq":"Një tabletë në 500 ml ujë.","en":"One tablet in 500 ml of water."}','{"sq":"Përmban natrium; kujdes në dieta me kufizim kripe.","en":"Contains sodium; take care on a salt-restricted diet."}','moderate','mineral'),
 ('a0000000-0000-4000-8000-000000000013','hyaluronic-acid','{"sq":"Acidi hialuronik","en":"Hyaluronic acid"}','{"Sodium hyaluronate"}','{"sq":"Molekulë që mban ujin, e prezente natyrshëm në lëkurë.","en":"A water-holding molecule present naturally in skin."}','{"sq":"Përdoret gjerësisht në rutinat e lëkurës.","en":"Widely used in skin routines."}','{"sq":"120 mg në ditë.","en":"120 mg daily."}','{"sq":"Pa efekte të njohura në doza normale.","en":"No known effects at normal intakes."}','emerging','other'),
 ('a0000000-0000-4000-8000-000000000014','iron','{"sq":"Hekuri bisglicinat","en":"Iron bisglycinate"}','{"Ferrous bisglycinate"}','{"sq":"Formë e lidhur me aminoacid, më e tolerueshme se sulfati.","en":"An amino-acid-bound form, gentler than sulphate."}','{"sq":"Kontribuon në transportin normal të oksigjenit në trup.","en":"Contributes to normal oxygen transport in the body."}','{"sq":"14–28 mg në ditë, me vitaminë C.","en":"14–28 mg daily, with vitamin C."}','{"sq":"Merr vetëm nëse është konstatuar nevoja. Mbaj larg fëmijëve.","en":"Take only if a need has been established. Keep away from children."}','strong','mineral')
on conflict (id) do update set slug = excluded.slug, name = excluded.name, summary = excluded.summary,
  benefits = excluded.benefits, dosage_notes = excluded.dosage_notes, safety_notes = excluded.safety_notes,
  evidence = excluded.evidence, category = excluded.category;

-- -----------------------------------------------------------------------------
-- Products (docs/11 §7)
-- -----------------------------------------------------------------------------
insert into products (id, slug, brand_id, name, subtitle, description, how_to_use, warnings, form, serving_size, dietary_tags, status, is_featured, published_at) values
 ('b0000000-0000-4000-8000-000000000001','now-vitamin-d3-4000','66666666-0000-4000-8000-000000000001','{"sq":"NOW Vitamina D3 4000 IU","en":"NOW Vitamin D3 4000 IU"}','{"sq":"Softgel me vaj ulliri","en":"Softgels in olive oil"}','{"sq":"Vitaminë D3 në formë kolekalciferol, e tretur në vaj ulliri për përthithje më të mirë. Një softgel në ditë mbulon nevojën e dimrit.","en":"Vitamin D3 as cholecalciferol, dissolved in olive oil for better absorption. One softgel a day covers the winter gap."}','{"sq":"Merr një softgel në ditë me një vakt.","en":"Take one softgel daily with a meal."}','{}','softgel','1 softgel','{gluten_free,non_gmo}','published',true,now() - interval '60 days'),
 ('b0000000-0000-4000-8000-000000000002','solgar-vitamin-c-1000','66666666-0000-4000-8000-000000000002','{"sq":"Solgar Vitamina C 1000 mg","en":"Solgar Vitamin C 1000 mg"}','{"sq":"100 kapsula vegjetale","en":"100 vegetable capsules"}','{"sq":"Vitaminë C në dozë të lartë, në kapsulë vegjetale pa mbushës të panevojshëm.","en":"High-dose vitamin C in a vegetable capsule with no unnecessary fillers."}','{"sq":"Një kapsulë në ditë, preferohet me ushqim.","en":"One capsule daily, preferably with food."}','{}','capsule','1 kapsulë','{vegan,gluten_free}','published',false,now() - interval '55 days'),
 ('b0000000-0000-4000-8000-000000000003','solgar-magnesium-bisglycinate','66666666-0000-4000-8000-000000000002','{"sq":"Solgar Magnez Bisglicinat","en":"Solgar Magnesium Bisglycinate"}','{"sq":"Formë e butë për stomakun","en":"A form that is gentle on the stomach"}','{"sq":"Magnez i lidhur me glicinë, që tolerohet mirë edhe në doza më të larta. Shumë e marrin në mbrëmje.","en":"Magnesium bound to glycine, well tolerated even at higher doses. Many take it in the evening."}','{"sq":"Dy kapsula në mbrëmje.","en":"Two capsules in the evening."}','{}','capsule','2 kapsula','{vegan,gluten_free}','published',false,now() - interval '50 days'),
 ('b0000000-0000-4000-8000-000000000004','now-zinc-picolinate-50','66666666-0000-4000-8000-000000000001','{"sq":"NOW Zink Pikolinat 50 mg","en":"NOW Zinc Picolinate 50 mg"}','{"sq":"120 kapsula","en":"120 capsules"}','{"sq":"Zink në formë pikolinat, e njohur për përthithje të mirë.","en":"Zinc as picolinate, known for good absorption."}','{"sq":"Një kapsulë në ditë me ushqim.","en":"One capsule daily with food."}','{"sq":"Mos merr me stomak bosh.","en":"Do not take on an empty stomach."}','capsule','1 kapsulë','{vegan,gluten_free,non_gmo}','published',false,now() - interval '48 days'),
 ('b0000000-0000-4000-8000-000000000005','jamieson-b12-1000','66666666-0000-4000-8000-000000000007','{"sq":"Jamieson B12 1000 µg","en":"Jamieson B12 1000 µg"}','{"sq":"Tableta sublinguale","en":"Sublingual tablets"}','{"sq":"B12 që shkrihet nën gjuhë, e dobishme për dietat vegane dhe për moshën e tretë.","en":"B12 that dissolves under the tongue, useful on vegan diets and in later life."}','{"sq":"Një tabletë nën gjuhë, në mëngjes.","en":"One tablet under the tongue, in the morning."}','{}','tablet','1 tabletë','{vegetarian,gluten_free}','published',false,now() - interval '45 days'),
 ('b0000000-0000-4000-8000-000000000006','terranova-b-complex','66666666-0000-4000-8000-000000000006','{"sq":"Terranova Kompleksi B","en":"Terranova B-Complex"}','{"sq":"Me bazë bimore","en":"With a botanical base"}','{"sq":"Të tetë vitaminat B bashkë me një bazë bimore, pa mbushës sintetikë.","en":"All eight B vitamins alongside a botanical base, with no synthetic fillers."}','{"sq":"Një kapsulë në ditë me ushqim.","en":"One capsule daily with food."}','{"sq":"Mund të ngjyrosë urinën të verdhë.","en":"May turn urine bright yellow."}','capsule','1 kapsulë','{vegan,gluten_free}','published',false,now() - interval '42 days'),
 ('b0000000-0000-4000-8000-000000000007','on-gold-standard-whey','66666666-0000-4000-8000-000000000003','{"sq":"ON Gold Standard Whey","en":"ON Gold Standard Whey"}','{"sq":"24 g proteinë për dozë","en":"24 g protein per serving"}','{"sq":"Përzierje izolat dhe koncentrat whey, që tretet lehtë në shaker. Standardi me të cilin krahasohen të tjerat.","en":"An isolate and concentrate whey blend that mixes easily in a shaker. The benchmark others are measured against."}','{"sq":"Një dozë në 250 ml ujë ose qumësht, pas stërvitjes.","en":"One scoop in 250 ml of water or milk, after training."}','{"sq":"Përmban qumësht dhe soje.","en":"Contains milk and soy."}','powder','30 g','{}','published',true,now() - interval '40 days'),
 ('b0000000-0000-4000-8000-000000000008','myprotein-impact-whey','66666666-0000-4000-8000-000000000004','{"sq":"MyProtein Impact Whey","en":"MyProtein Impact Whey"}','{"sq":"Raport i mirë çmim-cilësi","en":"Strong value for money"}','{"sq":"Koncentrat whey me 21 g proteinë për dozë, në shije luleshtrydhe.","en":"Whey concentrate with 21 g protein per serving, in strawberry."}','{"sq":"Një dozë pas stërvitjes.","en":"One scoop after training."}','{"sq":"Përmban qumësht.","en":"Contains milk."}','powder','25 g','{}','published',false,now() - interval '38 days'),
 ('b0000000-0000-4000-8000-000000000009','myprotein-vegan-blend','66666666-0000-4000-8000-000000000004','{"sq":"MyProtein Përzierje Vegane","en":"MyProtein Vegan Blend"}','{"sq":"Bizele dhe oriz","en":"Pea and rice"}','{"sq":"Përzierje bimore që dhuron profil të plotë aminoacidesh, pa qumësht dhe pa soje.","en":"A plant blend giving a complete amino-acid profile, free from dairy and soy."}','{"sq":"Një dozë në 300 ml ujë ose pije bimore.","en":"One scoop in 300 ml of water or a plant drink."}','{}','powder','30 g','{vegan,lactose_free}','published',false,now() - interval '36 days'),
 ('b0000000-0000-4000-8000-00000000000a','on-micronised-creatine','66666666-0000-4000-8000-000000000003','{"sq":"ON Kreatina e Mikronizuar","en":"ON Micronised Creatine"}','{"sq":"Pa shije, tretet shpejt","en":"Unflavoured, mixes fast"}','{"sq":"Kreatinë monohidrat e mikronizuar, pa shije, që tretet pa kokrriza.","en":"Micronised creatine monohydrate, unflavoured, dissolving without grit."}','{"sq":"5 g në ditë, në ujë ose lëng.","en":"5 g daily, in water or juice."}','{"sq":"Pi ujë të bollshëm.","en":"Drink plenty of water."}','powder','5 g','{vegan,gluten_free}','published',false,now() - interval '34 days'),
 ('b0000000-0000-4000-8000-00000000000b','biotechusa-100-creatine','66666666-0000-4000-8000-000000000005','{"sq":"BioTechUSA 100% Kreatinë","en":"BioTechUSA 100% Creatine"}','{"sq":"300 g, pa aditivë","en":"300 g, no additives"}','{"sq":"Kreatinë monohidrat e pastër, një përbërës i vetëm.","en":"Pure creatine monohydrate, a single ingredient."}','{"sq":"5 g në ditë.","en":"5 g daily."}','{}','powder','5 g','{vegan,gluten_free}','published',false,now() - interval '32 days'),
 ('b0000000-0000-4000-8000-00000000000c','now-omega-3-1000','66666666-0000-4000-8000-000000000001','{"sq":"NOW Omega-3 1000 mg","en":"NOW Omega-3 1000 mg"}','{"sq":"180 mg EPA / 120 mg DHA","en":"180 mg EPA / 120 mg DHA"}','{"sq":"Vaj peshku i distiluar molekularisht, i testuar për metale të rënda.","en":"Molecularly distilled fish oil, tested for heavy metals."}','{"sq":"Dy softgel në ditë me vakt.","en":"Two softgels daily with a meal."}','{"sq":"Përmban peshk.","en":"Contains fish."}','softgel','2 softgel','{gluten_free}','published',false,now() - interval '30 days'),
 ('b0000000-0000-4000-8000-00000000000d','solgar-omega-3-6-9','66666666-0000-4000-8000-000000000002','{"sq":"Solgar Omega 3-6-9","en":"Solgar Omega 3-6-9"}','{"sq":"Peshk, li dhe borage","en":"Fish, flax and borage"}','{"sq":"Kombinim i tre familjeve të acideve yndyrore në një softgel.","en":"Three fatty-acid families combined in one softgel."}','{"sq":"Një softgel në ditë me vakt.","en":"One softgel daily with a meal."}','{"sq":"Përmban peshk.","en":"Contains fish."}','softgel','1 softgel','{gluten_free}','published',false,now() - interval '28 days'),
 ('b0000000-0000-4000-8000-00000000000e','swisse-collagen-peptides','66666666-0000-4000-8000-000000000008','{"sq":"Swisse Peptide Kolagjeni","en":"Swisse Collagen Peptides"}','{"sq":"Me vitaminë C","en":"With vitamin C"}','{"sq":"Peptide kolagjeni të hidrolizuara me vitaminë C, që kontribuon në formimin normal të kolagjenit. Pa shije, tretet në kafe.","en":"Hydrolysed collagen peptides with vitamin C, which contributes to normal collagen formation. Unflavoured, dissolves in coffee."}','{"sq":"Një dozë 10 g në ditë.","en":"One 10 g scoop daily."}','{"sq":"Nuk është vegan.","en":"Not vegan."}','powder','10 g','{gluten_free,lactose_free}','published',false,now() - interval '26 days'),
 ('b0000000-0000-4000-8000-00000000000f','terranova-ashwagandha','66666666-0000-4000-8000-000000000006','{"sq":"Terranova Ashwagandha","en":"Terranova Ashwagandha"}','{"sq":"KSM-66, e standardizuar","en":"KSM-66, standardised"}','{"sq":"Ekstrakt rrënjë i standardizuar në withanolide, me bazë bimore.","en":"A root extract standardised for withanolides, on a botanical base."}','{"sq":"Një kapsulë në ditë me ushqim.","en":"One capsule daily with food."}','{"sq":"Jo në shtatzëni ose gjidhënie.","en":"Not in pregnancy or while breastfeeding."}','capsule','1 kapsulë','{vegan,gluten_free}','published',false,now() - interval '24 days'),
 ('b0000000-0000-4000-8000-000000000010','now-rhodiola-500','66666666-0000-4000-8000-000000000001','{"sq":"NOW Rhodiola 500 mg","en":"NOW Rhodiola 500 mg"}','{"sq":"3% rosavina","en":"3% rosavins"}','{"sq":"Ekstrakt rrënjë rhodiola, i standardizuar në rosavina dhe salidrozid.","en":"Rhodiola root extract, standardised for rosavins and salidroside."}','{"sq":"Një kapsulë në mëngjes.","en":"One capsule in the morning."}','{"sq":"Mund të ndikojë gjumin nëse merret mbrëmje.","en":"May affect sleep if taken late."}','capsule','1 kapsulë','{vegan,gluten_free}','published',false,now() - interval '22 days'),
 ('b0000000-0000-4000-8000-000000000011','jamieson-melatonin-3','66666666-0000-4000-8000-000000000007','{"sq":"Jamieson Melatonina 3 mg","en":"Jamieson Melatonin 3 mg"}','{"sq":"Tableta të ndashme","en":"Splittable tablets"}','{"sq":"Melatoninë në tableta që mund të ndahen, për të gjetur dozën më të vogël efektive.","en":"Melatonin in splittable tablets, so the smallest effective dose can be found."}','{"sq":"Gjysmë ose një tabletë, 30 minuta para gjumit.","en":"Half a tablet or one, thirty minutes before bed."}','{"sq":"Shkakton përgjumje. Mos vozit pas marrjes. Jo në shtatzëni, gjidhënie ose nën 18 vjeç. Konsulto profesionistin e shëndetit nëse merr mjekim.","en":"Causes drowsiness. Do not drive after taking. Not in pregnancy, while breastfeeding, or under 18. Consult a healthcare professional if you take medication."}','tablet','1 tabletë','{vegetarian,gluten_free}','published',false,now() - interval '20 days'),
 ('b0000000-0000-4000-8000-000000000012','now-curcumin','66666666-0000-4000-8000-000000000001','{"sq":"NOW Kurkumina","en":"NOW Curcumin"}','{"sq":"95% kurkuminoide","en":"95% curcuminoids"}','{"sq":"Ekstrakt shafrani i Indisë i standardizuar, me piperinë për përthithje.","en":"A standardised turmeric extract with piperine for absorption."}','{"sq":"Një kapsulë në ditë me vakt.","en":"One capsule daily with a meal."}','{"sq":"Bisedo me mjekun nëse merr antikoagulantë.","en":"Speak to your doctor if you take anticoagulants."}','capsule','1 kapsulë','{vegan,gluten_free}','published',false,now() - interval '18 days'),
 ('b0000000-0000-4000-8000-000000000013','biotechusa-probiotic','66666666-0000-4000-8000-000000000005','{"sq":"BioTechUSA Probiotik","en":"BioTechUSA Probiotic"}','{"sq":"10 miliardë CFU","en":"10 billion CFU"}','{"sq":"Përzierje shumështërore me kapsulë të mbrojtur nga acidi i stomakut.","en":"A multi-strain blend in a capsule protected from stomach acid."}','{"sq":"Një kapsulë në mëngjes, me stomak bosh.","en":"One capsule in the morning, on an empty stomach."}','{"sq":"Ruaj në frigorifer pas hapjes.","en":"Refrigerate after opening."}','capsule','1 kapsulë','{vegetarian,gluten_free}','published',false,now() - interval '16 days'),
 ('b0000000-0000-4000-8000-000000000014','now-psyllium-husk','66666666-0000-4000-8000-000000000001','{"sq":"NOW Lëvozhgë Psyllium","en":"NOW Psyllium Husk"}','{"sq":"500 g pluhur","en":"500 g powder"}','{"sq":"Fibër e tretshme e pastër, pa sheqer dhe pa aroma.","en":"Pure soluble fibre, with no sugar and no flavourings."}','{"sq":"Një lugë çaji në një gotë të plotë uji.","en":"One teaspoon in a full glass of water."}','{"sq":"Merr gjithmonë me shumë lëng.","en":"Always take with plenty of liquid."}','powder','5 g','{vegan,gluten_free}','published',false,now() - interval '14 days'),
 ('b0000000-0000-4000-8000-000000000015','myprotein-electrolyte-tabs','66666666-0000-4000-8000-000000000004','{"sq":"MyProtein Tableta Elektrolite","en":"MyProtein Electrolyte Tabs"}','{"sq":"Shije limoni","en":"Lemon flavour"}','{"sq":"Tableta që shkrihen në ujë, për stërvitje të gjata ose ditë të nxehta.","en":"Tablets that dissolve in water, for long sessions or hot days."}','{"sq":"Një tabletë në 500 ml ujë.","en":"One tablet in 500 ml of water."}','{"sq":"Përmban natrium.","en":"Contains sodium."}','tablet','1 tabletë','{vegan,gluten_free,sugar_free}','published',false,now() - interval '12 days'),
 ('b0000000-0000-4000-8000-000000000016','swisse-hair-skin-nails','66666666-0000-4000-8000-000000000008','{"sq":"Swisse Flokë Lëkurë Thonj","en":"Swisse Hair Skin Nails"}','{"sq":"Me biotinë dhe zink","en":"With biotin and zinc"}','{"sq":"Formulë me acid hialuronik, vitaminë C dhe zink, që kontribuojnë në ruajtjen e lëkurës normale.","en":"A formula with hyaluronic acid, vitamin C and zinc, which contribute to the maintenance of normal skin."}','{"sq":"Një tabletë në ditë me ushqim.","en":"One tablet daily with food."}','{}','tablet','1 tabletë','{gluten_free}','published',false,now() - interval '10 days'),
 ('b0000000-0000-4000-8000-000000000017','biocode-shaker-600','66666666-0000-4000-8000-000000000001','{"sq":"BIOCODE Shaker 600 ml","en":"BIOCODE Shaker 600 ml"}','{"sq":"Pa BPA, me rrjetë","en":"BPA-free, with mixing mesh"}','{"sq":"Shaker 600 ml me rrjetë të brendshme dhe kapak që mbyll fort.","en":"A 600 ml shaker with an internal mesh and a lid that seals properly."}','{"sq":"Lahet me dorë për ruajtje më të gjatë.","en":"Hand wash to keep it longer."}','{}','other',null,'{}','published',false,now() - interval '8 days'),
 ('b0000000-0000-4000-8000-000000000018','pako-imuniteti','66666666-0000-4000-8000-000000000001','{"sq":"Pako Imuniteti","en":"Immunity Bundle"}','{"sq":"D3, C dhe zink bashkë","en":"D3, C and zinc together"}','{"sq":"Tre bazat e rutinës së dimrit në një pako: vitaminë D3, vitaminë C dhe zink. Kursen kundrejt blerjes veç e veç.","en":"The three winter-routine basics in one pack: vitamin D3, vitamin C and zinc. Cheaper than buying them separately."}','{"sq":"Ndiq udhëzimet e secilit produkt.","en":"Follow the directions on each product."}','{}','other','1 set','{gluten_free}','published',false,now() - interval '6 days')
on conflict (id) do update set slug = excluded.slug, brand_id = excluded.brand_id, name = excluded.name,
  subtitle = excluded.subtitle, description = excluded.description, how_to_use = excluded.how_to_use,
  warnings = excluded.warnings, form = excluded.form, serving_size = excluded.serving_size,
  dietary_tags = excluded.dietary_tags, status = excluded.status, is_featured = excluded.is_featured,
  published_at = excluded.published_at;
